#!/usr/bin/env python3
"""Assign GAFF2 types to the formal RESP-charged zwitterion and export GROMACS inputs."""

from __future__ import annotations

import argparse
import hashlib
import json
import math
from pathlib import Path
import re
import shutil
import subprocess
from typing import Any

import numpy as np
import parmed as pmd

try:
    from .validate_parameters import parse_itp_atoms, parse_mol2_atoms, validate_atom_table
except ImportError:  # Direct script execution from this directory.
    from validate_parameters import parse_itp_atoms, parse_mol2_atoms, validate_atom_table


SECTION_PATTERN = re.compile(r"^\s*\[\s*([^]]+)\s*\]")


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def run_command(command: list[str], cwd: Path, log_path: Path) -> None:
    completed = subprocess.run(
        command,
        cwd=cwd,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        check=False,
    )
    log_path.write_text(completed.stdout, encoding="utf-8")
    if completed.returncode != 0:
        raise RuntimeError(
            f"command failed with exit code {completed.returncode}: {' '.join(command)}; "
            f"see {log_path}"
        )


def read_resp_charges(path: Path) -> np.ndarray:
    values = np.array(
        [float(line.strip()) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()],
        dtype=float,
    )
    if len(values) == 0 or not np.all(np.isfinite(values)):
        raise ValueError("RESP charge file is empty or contains non-finite values")
    if abs(math.fsum(float(value) for value in values)) > 1e-4:
        raise ValueError("RESP charge file is not net neutral")
    return values


def require_usable_resp_metadata(path: Path) -> dict[str, Any]:
    metadata = json.loads(path.read_text(encoding="utf-8"))
    if metadata.get("status") != "resp_fit_complete_pending_review":
        raise ValueError(
            "RESP result is not eligible for GAFF2 conversion: "
            f"status={metadata.get('status')!r}"
        )
    screen = metadata.get("charge_validation", {})
    if screen.get("passed_conservative_magnitude_screen") is not True:
        raise ValueError("RESP atomic-charge magnitude screen did not pass")
    return metadata


def read_sdf(path: Path) -> tuple[list[str], np.ndarray]:
    lines = path.read_text(encoding="utf-8").splitlines()
    if len(lines) < 4:
        raise ValueError(f"invalid SDF file: {path}")
    try:
        atom_count = int(lines[3][0:3])
    except ValueError as error:
        raise ValueError(f"invalid SDF counts line in {path}: {lines[3]}") from error
    atom_lines = lines[4 : 4 + atom_count]
    if len(atom_lines) != atom_count:
        raise ValueError(f"truncated SDF atom block in {path}")
    elements = [line[31:34].strip() for line in atom_lines]
    coordinates = np.array(
        [[float(line[0:10]), float(line[10:20]), float(line[20:30])] for line in atom_lines],
        dtype=float,
    )
    return elements, coordinates


def mol2_elements(path: Path) -> list[str]:
    elements = []
    for atom in parse_mol2_atoms(path):
        name = str(atom["name"])
        match = re.match(r"([A-Za-z]+)", name)
        if match is None:
            raise ValueError(f"cannot infer element from MOL2 atom name: {name}")
        letters = match.group(1)
        elements.append(letters[0].upper())
    return elements


def split_parmed_topology(full_topology: Path, itp_path: Path) -> None:
    lines = full_topology.read_text(encoding="utf-8").splitlines()
    sections: dict[str, int] = {}
    for index, line in enumerate(lines):
        match = SECTION_PATTERN.match(line)
        if match:
            sections.setdefault(match.group(1).strip().lower(), index)
    required = {"defaults", "atomtypes", "moleculetype", "system", "molecules"}
    missing = sorted(required - sections.keys())
    if missing:
        raise ValueError(f"ParmEd GROMACS topology lacks sections: {missing}")
    if not sections["defaults"] < sections["atomtypes"] < sections["moleculetype"] < sections["system"]:
        raise ValueError("unexpected section order in ParmEd GROMACS topology")
    header = [
        "; GAFF2 parameters generated by AmberTools and converted by ParmEd.",
        "; The [ defaults ] section is supplied by amber14sb.ff/forcefield.itp.",
        "",
    ]
    body = lines[sections["atomtypes"] : sections["system"]]
    itp_path.write_text("\n".join(header + body).rstrip() + "\n", encoding="utf-8")


def write_system_topology(path: Path) -> None:
    path.write_text(
        "; GAFF2 solute with GROMACS-distributed Amber14SB defaults and TIP3P water.\n"
        "#include \"amber14sb.ff/forcefield.itp\"\n"
        "#include \"zil.itp\"\n"
        "#include \"amber14sb.ff/tip3p.itp\"\n\n"
        "[ system ]\n"
        "Single ZIL molecule in excess water\n\n"
        "[ molecules ]\n"
        "ZIL     1\n",
        encoding="utf-8",
    )


def write_gro_from_sdf(prmtop: Path, sdf: Path, output: Path) -> None:
    _, coordinates = read_sdf(sdf)
    structure = pmd.load_file(str(prmtop))
    if len(structure.atoms) != len(coordinates):
        raise ValueError(f"atom count mismatch between {prmtop} and {sdf}")
    structure.coordinates = coordinates
    structure.box = None
    structure.save(str(output), format="gro", overwrite=True)


def build_metadata(
    work_root: Path,
    resp_dir: Path,
    artifact_dir: Path,
    topology_dir: Path,
    max_charge_error: float,
    attention_lines: list[str],
) -> dict[str, Any]:
    tracked = [
        artifact_dir / "zil_gaff2.mol2",
        artifact_dir / "zil.frcmod",
        artifact_dir / "zil.prmtop",
        artifact_dir / "zil.inpcrd",
        topology_dir / "zil.itp",
        topology_dir / "zil_folded.gro",
        topology_dir / "zil_intermediate.gro",
        topology_dir / "zil_extended.gro",
        topology_dir / "system.top",
    ]
    return {
        "status": "gaff2_conversion_complete_pending_validation",
        "resp_metadata_sha256": sha256(resp_dir / "resp_metadata.json"),
        "large_working_directory": str(work_root),
        "atom_count": len(parse_mol2_atoms(artifact_dir / "zil_gaff2.mol2")),
        "total_charge_e": math.fsum(
            float(atom["charge"]) for atom in parse_mol2_atoms(artifact_dir / "zil_gaff2.mol2")
        ),
        "max_mol2_vs_resp_charge_error_e": max_charge_error,
        "parmchk2_attention_lines": attention_lines,
        "requires_manual_frcmod_review": bool(attention_lines),
        "software": {
            "ambertools": "24.8",
            "parmed": pmd.__version__,
        },
        "outputs": {str(path): sha256(path) for path in tracked},
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--resp-dir", type=Path, required=True)
    parser.add_argument("--work-root", type=Path, required=True)
    parser.add_argument("--artifact-dir", type=Path, required=True)
    parser.add_argument("--topology-dir", type=Path, required=True)
    args = parser.parse_args()

    resp_dir = args.resp_dir.resolve()
    work_root = args.work_root.resolve()
    artifact_dir = args.artifact_dir.resolve()
    topology_dir = args.topology_dir.resolve()
    work_root.mkdir(parents=True, exist_ok=True)
    artifact_dir.mkdir(parents=True, exist_ok=True)
    topology_dir.mkdir(parents=True, exist_ok=True)

    require_usable_resp_metadata(resp_dir / "resp_metadata.json")
    charges = read_resp_charges(resp_dir / "resp_charges.txt")
    input_sdf = resp_dir / "zil_intermediate.sdf"
    sdf_elements, _ = read_sdf(input_sdf)
    if len(sdf_elements) != len(charges):
        raise ValueError("SDF atom count does not match RESP charge count")

    mol2_path = work_root / "zil_gaff2.mol2"
    run_command(
        [
            "antechamber", "-i", str(input_sdf), "-fi", "mdl",
            "-o", str(mol2_path), "-fo", "mol2", "-at", "gaff2",
            "-c", "rc", "-cf", str(resp_dir / "resp_charges.txt"),
            "-nc", "0", "-m", "1", "-rn", "ZIL", "-eq", "0",
            "-seq", "n", "-pf", "y", "-s", "2",
        ],
        cwd=work_root,
        log_path=work_root / "antechamber.log",
    )
    if mol2_elements(mol2_path) != sdf_elements:
        raise ValueError("Antechamber changed atom order relative to the RESP SDF")
    mol2_atoms = parse_mol2_atoms(mol2_path)
    validate_atom_table(mol2_atoms, expected_charge=0.0, tolerance=1e-4)
    mol2_charges = np.array([float(atom["charge"]) for atom in mol2_atoms])
    max_charge_error = float(np.max(np.abs(mol2_charges - charges)))
    if max_charge_error > 5e-6:
        raise ValueError(f"Antechamber altered RESP charges by {max_charge_error:.3g} e")

    frcmod_path = work_root / "zil.frcmod"
    run_command(
        ["parmchk2", "-i", str(mol2_path), "-f", "mol2", "-o", str(frcmod_path), "-s", "gaff2"],
        cwd=work_root,
        log_path=work_root / "parmchk2.log",
    )
    tleap_input = work_root / "tleap.in"
    tleap_input.write_text(
        "source leaprc.gaff2\n"
        "ZIL = loadmol2 zil_gaff2.mol2\n"
        "loadamberparams zil.frcmod\n"
        "check ZIL\n"
        "saveamberparm ZIL zil.prmtop zil.inpcrd\n"
        "savepdb ZIL zil.pdb\n"
        "quit\n",
        encoding="utf-8",
    )
    run_command(
        ["tleap", "-f", tleap_input.name],
        cwd=work_root,
        log_path=work_root / "tleap.stdout.log",
    )

    prmtop_path = work_root / "zil.prmtop"
    inpcrd_path = work_root / "zil.inpcrd"
    structure = pmd.load_file(str(prmtop_path), xyz=str(inpcrd_path))
    if len(structure.atoms) != len(charges):
        raise ValueError("Amber topology atom count does not match RESP charge count")
    amber_charge = math.fsum(float(atom.charge) for atom in structure.atoms)
    if abs(amber_charge) > 1e-4:
        raise ValueError(f"Amber topology is not net neutral: {amber_charge:.8f} e")
    full_topology = work_root / "zil_full.top"
    structure.save(str(full_topology), format="gromacs", overwrite=True)
    split_parmed_topology(full_topology, topology_dir / "zil.itp")
    write_system_topology(topology_dir / "system.top")

    for label in ("folded", "intermediate", "extended"):
        write_gro_from_sdf(
            prmtop_path,
            resp_dir / f"zil_{label}.sdf",
            topology_dir / f"zil_{label}.gro",
        )

    itp_atoms = parse_itp_atoms(topology_dir / "zil.itp")
    validate_atom_table(itp_atoms, expected_charge=0.0, tolerance=1e-4)
    if [str(atom["name"]) for atom in mol2_atoms] != [str(atom["name"]) for atom in itp_atoms]:
        raise ValueError("MOL2 and GROMACS ITP atom names/order differ")

    for source in (
        mol2_path, frcmod_path, prmtop_path, inpcrd_path,
        work_root / "antechamber.log", work_root / "parmchk2.log",
        work_root / "tleap.stdout.log", work_root / "leap.log",
    ):
        if source.is_file():
            shutil.copy2(source, artifact_dir / source.name)

    attention_lines = [
        line.strip()
        for line in frcmod_path.read_text(encoding="utf-8").splitlines()
        if "ATTN" in line.upper() or "USING THE DEFAULT VALUE" in line.upper()
    ]
    metadata = build_metadata(
        work_root, resp_dir, artifact_dir, topology_dir, max_charge_error, attention_lines
    )
    metadata_path = artifact_dir / "gaff2_metadata.json"
    metadata_path.write_text(json.dumps(metadata, indent=2) + "\n", encoding="utf-8")
    print(metadata_path)


if __name__ == "__main__":
    main()
